version: '3.8'

services:
  webcrawler:
    build: .
    container_name: webcrawler
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - TIMEOUT=30
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webcrawler-network

  # Optional: Redis für Caching (für zukünftige Features)
  # redis:
  #   image: redis:7-alpine
  #   container_name: webcrawler-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - webcrawler-network

networks:
  webcrawler-network:
    driver: bridge

# volumes:
#   redis-data: 