name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build -o webcrawler .

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/webcrawler-linux-amd64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o build/webcrawler-windows-amd64.exe .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/webcrawler-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o build/webcrawler-darwin-arm64 .

    - name: Create checksums
      run: |
        cd build
        sha256sum webcrawler-* > checksums.txt

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: webcrawler-binaries
        path: build/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/webcrawler:latest
          ${{ secrets.DOCKER_USERNAME }}/webcrawler:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 