# This workflow is disabled - using ci-simple.yml instead
name: CI (Disabled)

on:
  # Disabled - using ci-simple.yml
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
    - name: This workflow is disabled
      run: echo "Use ci-simple.yml instead" 