name: Issue Automation

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened]

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  pr-labeler:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  stale-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-issue-label: 'no-remove'
        stale-pr-label: 'no-remove'
        days-before-stale: 30
        days-before-close: 7

  welcome-new-contributors:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const { data: commits } = await github.rest.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.pull_request.head.sha,
          });
          
          const isFirstTimeContributor = commits.some(commit => 
            commit.author && commit.author.login !== context.payload.pull_request.user.login
          );
          
          if (!isFirstTimeContributor) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🎉 Welcome to WebCrawler! Thank you for your first contribution!\n\nWe're excited to have you on board. Our maintainers will review your PR soon.`
            });
          } 